# Site settings
title: Rhino.Inside.Revit Documentation
# email: brian@mcneel.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
editme_github_base_url: "mcneel/rhino.inside-revit"
description: Rhino.Inside.Revit Documentation
copyright: Robert McNeel & Associates
version: beta
language: en

gems:
  - jekyll-sitemap

github_username:  mcneel
simple_search: http://google.com/search

# Build settings
encoding: utf-8

# If we decide that we want to use kramdown over redcarpet, syntax
# highlighting is performed by turning on the following options and
# including/running highlight.js (https://highlightjs.org/) at the
# top of pages that need it (probably just add to head.html)
#markdown: redcarpet
markdown: kramdown
kramdown:
  input: GFM

safe: false

collections_dir: pages

collections:
  en:
    output: true
    permalink: /en/:path

# set the attribute defaults for site contents
defaults:
  - scope:
      path: "" # all files
    values:
      layout: page-list-toc

  - scope:
      path: "" # all files
      type: en # in this collection
    values:
      language: en
      authors: ['scott_davidson']

  - scope:
      path: "pages/*/beta"
    values:
      version: beta

  - scope:
      path: "pages/*/1.0"
    values:
      version: 1.0

  - scope:
      path: "pages/*/*/guides"
    values:
      categories: ['guides']

  - scope:
      path: "pages/*/*/reference"
    values:
      categories: ['reference']

  - scope:
      path: "pages/*/*/samples"
    values:
      categories: ['samples']
