name: build_docs
on: workflow_dispatch

jobs:
  build_docs:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1

      - name: prep sandcastle
        run: |
          nuget install EWSoftware.SHFB -o packages
          nuget install EWSoftware.SHFB.NETFramework -o packages

      - name: build documentation
        run: msbuild script\cibuild_docs.msbuild -v:m

      # - name: upload docs
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: all-docs
      #     path: docs/api

      - name: commit & publish
        run: bash script\publish_docs.sh docs\api
