name: build_docs
on: workflow_dispatch

jobs:
  build_docs:
    runs-on: windows-latest
    steps:
      - name: prep repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}

      - name: prep msbuild
        uses: microsoft/setup-msbuild@v1

      - name: prep sandcastle
        run: |
          nuget install EWSoftware.SHFB -o packages
          nuget install EWSoftware.SHFB.NETFramework -o packages\components
          nuget install ResolveThirdPartyReferenceLinks -o packages\components -version "0.1.0-beta"

      - name: build documentation
        run: msbuild script/cibuild_docs.msbuild -v:m

      # - name: upload docs
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: all-docs
      #     path: docs/api/1.0

      - name: commit & publish
        run: |
          git config user.name mcneel-build
          git config user.email bozo@mcneel.com
          git add -A docs/api/
          git commit -m "Publish!"
          git push
